---
default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= 'salas' %>
  username: <%= 'postgres' %>
  password: <%= 'postgres' %>
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>
  pool: <%= ENV["POSTGRESQL_POOL"] || 5 %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>

development:
  <<: *default

test:
  <<: *default
  database: test

production:
  <<: *default

